/**
 * Synthetic fixtures for the Flow Workbench (ADR-0006 boundary — no
 * real-farmer data). Modeled on the repository-owned registry tables from
 * db/migrations/0001_registration_pilot.sql and 0003_contract_closures.sql.
 *
 * Scenarios follow the canonical cases named in WB-1/WB-2 acceptance
 * criteria: a direct registration, a two-activity split, an ambiguous
 * clarification, a retry, an expired draft, an ignored message, an unmapped
 * intake item, and a deterministic eval replay.
 */
import type {
  AgentRun,
  AgentRunAttempt,
  AgentRunEvent,
  DailyMetric,
  EvalCaseResult,
  EvalRun,
  Farm,
  FarmActivity,
  FarmObservation,
  FunnelStage,
  HealthPanel,
  ImportBatch,
  RegistrationMessage,
  SeasonField,
} from "./types";

const T = "+02:00"; // Europe/Amsterdam, CEST

// ── Farms & fields ───────────────────────────────────────────────────────────

export const farms: Farm[] = [
  { farmId: "bijovira-synthetic", name: "bi-jovira (synthetic)" },
  { farmId: "demo-acres", name: "Demo Acres (synthetic)" },
];

export const seasonFields: SeasonField[] = [
  {
    id: 1,
    farmId: "bijovira-synthetic",
    jaar: 2026,
    name: "de pompoen",
    cropNl: "pompoen",
  },
  {
    id: 2,
    farmId: "bijovira-synthetic",
    jaar: 2026,
    name: "uien noord",
    cropNl: "uien",
  },
  {
    id: 3,
    farmId: "bijovira-synthetic",
    jaar: 2026,
    name: "achter oost",
    cropNl: "wortelen",
  },
  {
    id: 4,
    farmId: "bijovira-synthetic",
    jaar: 2026,
    name: "voedselbos",
    cropNl: "fruitbos",
  },
  {
    id: 5,
    farmId: "demo-acres",
    jaar: 2026,
    name: "veld A",
    cropNl: "aardappelen",
  },
];

// ── Registration messages (intake, in order) ─────────────────────────────────

export const registrationMessages: RegistrationMessage[] = [
  {
    id: 101,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-01T08:12:00${T}`,
    text: "Vanochtend 2 uur gewied in de pompoen, en nog 1 uur onderhoud tractor.",
    entryId: "E-0901-01",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 102,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "out",
    sentAt: `2026-09-01T08:12:04${T}`,
    text: "Geregistreerd: 2 u wieden in de pompoen en 1 u tractor-onderhoud. Klopt dit?",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 103,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-01T10:40:00${T}`,
    text: "1 uur geschoffeld bij de uien",
    metadata: { decision: "asked" },
    identityState: "mapped",
  },
  {
    id: 104,
    farmId: "bijovira-synthetic",
    reporterId: "tg:agent",
    direction: "out",
    sentAt: `2026-09-01T10:40:03${T}`,
    text: "Bedoel je uien noord of het voedselbos? Daar staat dit jaar ook ui.",
    metadata: { decision: "asked" },
    identityState: "mapped",
  },
  {
    id: 105,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-01T13:05:00${T}`,
    text: "gisteren 3 uur beregend, pomp de hele dag aan gehad",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 106,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-01T15:22:00${T}`,
    text: "even koffie met de buren, further niks gedaan",
    metadata: { decision: "ignored", reason: "not_work" },
    identityState: "mapped",
  },
  {
    id: 107,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-02T09:03:00${T}`,
    text: "morgen spuiten op achter oost",
    entryId: "E-0902-01",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 108,
    farmId: "bijovira-synthetic",
    reporterId: "tg:agent",
    direction: "out",
    sentAt: `2026-09-02T09:03:05${T}`,
    text: "Welk product en welke dosering? Dan zet ik de spuitregistratie klaar.",
    metadata: { decision: "asked" },
    identityState: "mapped",
  },
  {
    id: 109,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-02T09:20:00${T}`,
    text: "ranja 2 l/ha",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 110,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-08-28T19:44:00${T}`,
    text: "2 uur gewied, 1 uur daarvan Joas",
    entryId: "E-0828-01",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 111,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-08-29T17:02:00${T}`,
    text: "vandaag veel regen, niet gewerkt",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 112,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-09-02T11:30:00${T}`,
    text: "kun je de wieden van dinsdag naar 2,5 uur zetten? was toch langer",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  {
    id: 113,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-08-30T09:00:00${T}`,
    text: "vraag: hoeveel uur deze week al?",
    metadata: { decision: "observed" },
    identityState: "mapped",
  },
  {
    id: 114,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-08-31T08:00:00${T}`,
    text: "wil je nog weten dat ik zaterdag om 7 uur kon beginnen",
    metadata: { decision: "asked" },
    identityState: "mapped",
  },
  {
    id: 115,
    farmId: "bijovira-synthetic",
    reporterId: "tg:cornelis-s",
    direction: "in",
    sentAt: `2026-08-31T08:00:01${T}`,
    text: "excuses dubbeltje",
    metadata: { decision: "registered" },
    identityState: "mapped",
  },
  // ── Unmapped intake (TG-5 / WB-1: identity_state=unmapped, no run) ─────────
  {
    id: 201,
    farmId: "bijovira-synthetic",
    reporterId: "tg:unknown-9f2",
    direction: "in",
    sentAt: `2026-09-03T07:58:00${T}`,
    text: "[source withheld — unmapped sender]",
    metadata: {},
    identityState: "unmapped",
    replayKey: "rk_01J9ZK7Q2M",
  },
  {
    id: 202,
    farmId: "demo-acres",
    reporterId: "tg:unknown-3a1",
    direction: "in",
    sentAt: `2026-09-03T08:31:00${T}`,
    text: "[source withheld — unmapped sender]",
    metadata: {},
    identityState: "unmapped",
    replayKey: "rk_01J9ZK8W4P",
  },
  {
    id: 203,
    farmId: "bijovira-synthetic",
    reporterId: "tg:unknown-9f2",
    direction: "in",
    sentAt: `2026-09-03T09:12:00${T}`,
    text: "[source withheld — unmapped sender]",
    metadata: {},
    identityState: "unmapped",
    replayKey: "rk_01J9ZK9D7T",
  },
];

// ── Agent runs ───────────────────────────────────────────────────────────────

export const agentRuns: AgentRun[] = [
  {
    runId: "0b3e6f2a-4c11-4a5e-9d21-8f5a01c3b001",
    farmId: "bijovira-synthetic",
    messageId: 101,
    entryId: "E-0901-01",
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.09.0",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:9f31ab",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-9f31ab01",
    retentionClass: "extended",
    startedAt: `2026-09-01T08:12:01${T}`,
    endedAt: `2026-09-01T08:12:07${T}`,
  },
  {
    runId: "1c4f7a3b-5d22-4b6f-ae32-9a6b12d4c002",
    farmId: "bijovira-synthetic",
    messageId: 103,
    conversationId: "conv-0901-10",
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "asked",
    validationStatus: "clarification_required",
    applicationVersion: "app-2026.09.0",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:9f31ab",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-a1b2c302",
    retentionClass: "extended",
    startedAt: `2026-09-01T10:40:01${T}`,
    endedAt: `2026-09-01T10:40:05${T}`,
  },
  {
    runId: "2d5a8b4c-6e33-4c7a-bf43-ab7c23e5d003",
    farmId: "bijovira-synthetic",
    messageId: 105,
    entryId: "E-0901-02",
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "retried",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.09.0",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:9f31ab",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-b2c3d403",
    retentionClass: "extended",
    startedAt: `2026-09-01T13:05:01${T}`,
    endedAt: `2026-09-01T13:05:41${T}`,
  },
  {
    runId: "3e6b9c5d-7f44-4d8b-ca54-bc8d34f6e004",
    farmId: "bijovira-synthetic",
    messageId: 106,
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "failed",
    businessDecision: "undecided",
    applicationVersion: "app-2026.09.0",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:9f31ab",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-c3d4e504",
    retentionClass: "standard",
    startedAt: `2026-09-01T15:22:01${T}`,
    endedAt: `2026-09-01T15:22:09${T}`,
  },
  {
    runId: "4f7cad6e-8a55-4e9c-db65-cd9e45a7f005",
    farmId: "bijovira-synthetic",
    messageId: 107,
    conversationId: "conv-0902-09",
    entryId: "E-0902-01",
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.09.1",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:b7d20c",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-d4e5f605",
    retentionClass: "extended",
    startedAt: `2026-09-02T09:03:01${T}`,
    endedAt: `2026-09-02T09:20:03${T}`,
  },
  {
    runId: "5a8dbe7f-9b66-4fad-ec76-deaf56b8a006",
    farmId: "bijovira-synthetic",
    messageId: 111,
    entryId: "E-0829-01",
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.08.4",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:8811fe",
    profileVersion: "bijovira-v2",
    vocabularyVersion: 3,
    schemaVersion: "0003",
    traceId: "tr-e5f6a706",
    retentionClass: "standard",
    startedAt: `2026-08-29T17:02:01${T}`,
    endedAt: `2026-08-29T17:02:06${T}`,
  },
  {
    runId: "6b9ecf8a-ac77-4abe-fd87-ebfa67c9b007",
    farmId: "bijovira-synthetic",
    messageId: 112,
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.09.1",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:b7d20c",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-f6a7b807",
    retentionClass: "extended",
    startedAt: `2026-09-02T11:30:01${T}`,
    endedAt: `2026-09-02T11:30:08${T}`,
  },
  {
    runId: "7cafda9b-bd88-4bcf-fe98-fcab78dac008",
    farmId: "bijovira-synthetic",
    messageId: 113,
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "observed",
    validationStatus: "passed",
    applicationVersion: "app-2026.08.4",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:8811fe",
    profileVersion: "bijovira-v2",
    vocabularyVersion: 3,
    schemaVersion: "0003",
    traceId: "tr-a7b8c908",
    retentionClass: "standard",
    startedAt: `2026-08-30T09:00:01${T}`,
    endedAt: `2026-08-30T09:00:04${T}`,
  },
  {
    runId: "8dbfebac-ce99-4cda-afa9-adbc89ebd009",
    farmId: "bijovira-synthetic",
    messageId: 114,
    conversationId: "conv-0831-08",
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "succeeded",
    businessDecision: "expired",
    validationStatus: "clarification_required",
    applicationVersion: "app-2026.08.4",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:8811fe",
    profileVersion: "bijovira-v2",
    vocabularyVersion: 3,
    schemaVersion: "0003",
    traceId: "tr-b8c9da09",
    retentionClass: "short",
    startedAt: `2026-08-31T08:00:01${T}`,
    endedAt: `2026-09-01T08:00:01${T}`,
  },
  {
    runId: "9ec0fcab-dfaa-4deb-adba-beac9afce010",
    farmId: "bijovira-synthetic",
    importBatchId: "imp-2526-excel",
    entryId: "E-0828-01",
    sourceKind: "import",
    environment: "staging",
    executionMode: "deterministic",
    executionStatus: "succeeded",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.08.4",
    modelProvider: "—",
    modelVersion: "—",
    promptConfigHash: "—",
    profileVersion: "bijovira-v2",
    vocabularyVersion: 3,
    schemaVersion: "0003",
    retentionClass: "standard",
    startedAt: `2026-08-28T14:00:00${T}`,
    endedAt: `2026-08-28T14:06:32${T}`,
  },
  {
    runId: "afd10dbc-eabb-4efc-9acb-cfbdab0def11",
    farmId: "bijovira-synthetic",
    messageId: 110,
    sourceKind: "replay",
    environment: "ci",
    executionMode: "deterministic",
    executionStatus: "succeeded",
    businessDecision: "registered",
    validationStatus: "passed",
    applicationVersion: "app-2026.09.1",
    modelProvider: "TestModel",
    modelVersion: "deterministic",
    promptConfigHash: "pc:b7d20c",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    evalRunId: "evl-001-v42-v43",
    retentionClass: "short",
    startedAt: `2026-09-02T16:00:00${T}`,
    endedAt: `2026-09-02T16:00:02${T}`,
  },
  {
    runId: "b0e21ecd-fbcc-4fad-9bcd-d0cebc1def12",
    farmId: "bijovira-synthetic",
    messageId: 115,
    sourceKind: "telegram",
    environment: "pilot",
    executionMode: "live",
    executionStatus: "running",
    businessDecision: "undecided",
    applicationVersion: "app-2026.09.1",
    modelProvider: "openai",
    modelVersion: "gpt-4.1-mini-2026-06",
    promptConfigHash: "pc:b7d20c",
    profileVersion: "bijovira-v3",
    vocabularyVersion: 4,
    schemaVersion: "0003",
    traceId: "tr-c9daeb12",
    retentionClass: "standard",
    startedAt: `2026-08-31T08:00:02${T}`,
  },
];

// ── Attempts (retries create a new attempt_id under the same run_id) ─────────

export const agentRunAttempts: AgentRunAttempt[] = [
  {
    attemptId: "att-003-1",
    runId: "2d5a8b4c-6e33-4c7a-bf43-ab7c23e5d003",
    attemptNumber: 1,
    status: "failed",
    traceId: "tr-b2c3d403",
    startedAt: `2026-09-01T13:05:01${T}`,
    endedAt: `2026-09-01T13:05:03${T}`,
    errorCode: "provider_429",
  },
  {
    attemptId: "att-003-2",
    runId: "2d5a8b4c-6e33-4c7a-bf43-ab7c23e5d003",
    attemptNumber: 2,
    status: "failed",
    traceId: "tr-b2c3d403",
    startedAt: `2026-09-01T13:05:13${T}`,
    endedAt: `2026-09-01T13:05:15${T}`,
    errorCode: "provider_429",
  },
  {
    attemptId: "att-003-3",
    runId: "2d5a8b4c-6e33-4c7a-bf43-ab7c23e5d003",
    attemptNumber: 3,
    status: "succeeded",
    traceId: "tr-b2c3d403",
    startedAt: `2026-09-01T13:05:33${T}`,
    endedAt: `2026-09-01T13:05:41${T}`,
  },
  {
    attemptId: "att-004-1",
    runId: "3e6b9c5d-7f44-4d8b-ca54-bc8d34f6e004",
    attemptNumber: 1,
    status: "failed",
    traceId: "tr-c3d4e504",
    startedAt: `2026-09-01T15:22:01${T}`,
    endedAt: `2026-09-01T15:22:09${T}`,
    errorCode: "provider_timeout",
  },
  {
    attemptId: "att-012-1",
    runId: "b0e21ecd-fbcc-4fad-9bcd-d0cebc1def12",
    attemptNumber: 1,
    status: "running",
    traceId: "tr-c9daeb12",
    startedAt: `2026-08-31T08:00:02${T}`,
  },
];

// ── Run events (ordered by sequence_number per run) ──────────────────────────

function events(
  runId: string,
  rows: Array<
    Omit<AgentRunEvent, "eventId" | "runId"> & { attemptId?: string }
  >,
): AgentRunEvent[] {
  return rows.map((row, index) => ({
    ...row,
    eventId: `evt-${runId.slice(-3)}-${index + 1}`,
    runId,
  }));
}

export const agentRunEvents: AgentRunEvent[] = [
  ...events("0b3e6f2a-4c11-4a5e-9d21-8f5a01c3b001", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-09-01T08:12:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 40,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-09-01T08:12:01${T}`,
      stage: "scope",
      executionStatus: "succeeded",
      durationMs: 25,
      actorKind: "worker",
      metadata: { farm: "bijovira-synthetic", reporter: "mapped" },
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-01T08:12:02${T}`,
      stage: "agent",
      executionStatus: "succeeded",
      durationMs: 3200,
      actorKind: "agent",
    },
    {
      sequenceNumber: 4,
      occurredAt: `2026-09-01T08:12:03${T}`,
      stage: "tool",
      executionStatus: "succeeded",
      durationMs: 210,
      actorKind: "tool",
      metadata: { tool: "resolve_parcel", args: "crop=pompoen" },
    },
    {
      sequenceNumber: 5,
      occurredAt: `2026-09-01T08:12:04${T}`,
      stage: "validation",
      executionStatus: "succeeded",
      durationMs: 90,
      actorKind: "validator",
      metadata: { rules: "split_hours,required_fields" },
    },
    {
      sequenceNumber: 6,
      occurredAt: `2026-09-01T08:12:04${T}`,
      stage: "confirmation",
      executionStatus: "succeeded",
      durationMs: 8,
      actorKind: "farmer",
      metadata: { reply: "Klopt dit? → auto-clear" },
    },
    {
      sequenceNumber: 7,
      occurredAt: `2026-09-01T08:12:05${T}`,
      stage: "transaction",
      executionStatus: "succeeded",
      durationMs: 60,
      actorKind: "database",
      metadata: { rows: 2, entryId: "E-0901-01" },
    },
    {
      sequenceNumber: 8,
      occurredAt: `2026-09-01T08:12:07${T}`,
      stage: "reply",
      executionStatus: "succeeded",
      durationMs: 45,
      actorKind: "worker",
    },
  ]),
  ...events("1c4f7a3b-5d22-4b6f-ae32-9a6b12d4c002", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-09-01T10:40:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 35,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-09-01T10:40:01${T}`,
      stage: "scope",
      executionStatus: "succeeded",
      durationMs: 20,
      actorKind: "worker",
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-01T10:40:02${T}`,
      stage: "tool",
      executionStatus: "succeeded",
      durationMs: 180,
      actorKind: "tool",
      metadata: { tool: "resolve_parcel", candidates: 2, buffer_m: 30 },
    },
    {
      sequenceNumber: 4,
      occurredAt: `2026-09-01T10:40:02${T}`,
      stage: "validation",
      executionStatus: "succeeded",
      durationMs: 40,
      actorKind: "validator",
      reasonCode: "ambiguous_parcel",
    },
    {
      sequenceNumber: 5,
      occurredAt: `2026-09-01T10:40:03${T}`,
      stage: "conversation",
      executionStatus: "succeeded",
      durationMs: 30,
      actorKind: "agent",
      metadata: { question: "uien noord of voedselbos?" },
    },
    {
      sequenceNumber: 6,
      occurredAt: `2026-09-01T10:40:05${T}`,
      stage: "reply",
      executionStatus: "succeeded",
      durationMs: 40,
      actorKind: "worker",
    },
  ]),
  ...events("2d5a8b4c-6e33-4c7a-bf43-ab7c23e5d003", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-09-01T13:05:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 30,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-09-01T13:05:01${T}`,
      stage: "agent",
      executionStatus: "failed",
      durationMs: 1800,
      actorKind: "agent",
      attemptId: "att-003-1",
      reasonCode: "provider_429",
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-01T13:05:13${T}`,
      stage: "retry",
      executionStatus: "failed",
      durationMs: 1600,
      actorKind: "agent",
      attemptId: "att-003-2",
      reasonCode: "provider_429",
    },
    {
      sequenceNumber: 4,
      occurredAt: `2026-09-01T13:05:33${T}`,
      stage: "retry",
      executionStatus: "succeeded",
      durationMs: 6100,
      actorKind: "agent",
      attemptId: "att-003-3",
    },
    {
      sequenceNumber: 5,
      occurredAt: `2026-09-01T13:05:38${T}`,
      stage: "tool",
      executionStatus: "succeeded",
      durationMs: 220,
      actorKind: "tool",
      attemptId: "att-003-3",
      metadata: { tool: "mm_to_m3ha", value: 30 },
    },
    {
      sequenceNumber: 6,
      occurredAt: `2026-09-01T13:05:39${T}`,
      stage: "validation",
      executionStatus: "succeeded",
      durationMs: 70,
      actorKind: "validator",
      attemptId: "att-003-3",
    },
    {
      sequenceNumber: 7,
      occurredAt: `2026-09-01T13:05:39${T}`,
      stage: "transaction",
      executionStatus: "succeeded",
      durationMs: 55,
      actorKind: "database",
      attemptId: "att-003-3",
      metadata: { rows: 2, entryId: "E-0901-02" },
    },
    {
      sequenceNumber: 8,
      occurredAt: `2026-09-01T13:05:41${T}`,
      stage: "reply",
      executionStatus: "succeeded",
      durationMs: 42,
      actorKind: "worker",
      attemptId: "att-003-3",
    },
  ]),
  ...events("3e6b9c5d-7f44-4d8b-ca54-bc8d34f6e004", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-09-01T15:22:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 28,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-09-01T15:22:01${T}`,
      stage: "agent",
      executionStatus: "failed",
      durationMs: 7600,
      actorKind: "agent",
      attemptId: "att-004-1",
      reasonCode: "provider_timeout",
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-01T15:22:09${T}`,
      stage: "reply",
      executionStatus: "failed",
      durationMs: 60,
      actorKind: "worker",
      reasonCode: "outage_notice_sent",
    },
  ]),
  ...events("4f7cad6e-8a55-4e9c-db65-cd9e45a7f005", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-09-02T09:03:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 30,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-09-02T09:03:02${T}`,
      stage: "validation",
      executionStatus: "succeeded",
      durationMs: 50,
      actorKind: "validator",
      reasonCode: "missing_input_product_dose",
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-02T09:03:05${T}`,
      stage: "conversation",
      executionStatus: "succeeded",
      durationMs: 35,
      actorKind: "agent",
      metadata: { question: "product + dosering?" },
    },
    {
      sequenceNumber: 4,
      occurredAt: `2026-09-02T09:20:00${T}`,
      stage: "confirmation",
      executionStatus: "succeeded",
      durationMs: 2100,
      actorKind: "farmer",
      metadata: { answer: "ranja 2 l/ha" },
    },
    {
      sequenceNumber: 5,
      occurredAt: `2026-09-02T09:20:02${T}`,
      stage: "validation",
      executionStatus: "succeeded",
      durationMs: 60,
      actorKind: "validator",
    },
    {
      sequenceNumber: 6,
      occurredAt: `2026-09-02T09:20:02${T}`,
      stage: "transaction",
      executionStatus: "succeeded",
      durationMs: 65,
      actorKind: "database",
      metadata: { rows: 1, entryId: "E-0902-01", inputs: 1 },
    },
    {
      sequenceNumber: 7,
      occurredAt: `2026-09-02T09:20:03${T}`,
      stage: "reply",
      executionStatus: "succeeded",
      durationMs: 40,
      actorKind: "worker",
    },
  ]),
  ...events("8dbfebac-ce99-4cda-afa9-adbc89ebd009", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-08-31T08:00:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 30,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-08-31T08:00:02${T}`,
      stage: "conversation",
      executionStatus: "succeeded",
      durationMs: 40,
      actorKind: "agent",
      metadata: { question: "wat wil je registreren?" },
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-01T08:00:01${T}`,
      stage: "expiry",
      executionStatus: "succeeded",
      durationMs: 10,
      actorKind: "worker",
      reasonCode: "asked_ttl_24h",
    },
  ]),
  ...events("6b9ecf8a-ac77-4abe-fd87-ebfa67c9b007", [
    {
      sequenceNumber: 1,
      occurredAt: `2026-09-02T11:30:01${T}`,
      stage: "persist",
      executionStatus: "succeeded",
      durationMs: 30,
      actorKind: "worker",
    },
    {
      sequenceNumber: 2,
      occurredAt: `2026-09-02T11:30:02${T}`,
      stage: "tool",
      executionStatus: "succeeded",
      durationMs: 90,
      actorKind: "tool",
      metadata: { tool: "find_activity", entryId: "E-0901-01" },
    },
    {
      sequenceNumber: 3,
      occurredAt: `2026-09-02T11:30:03${T}`,
      stage: "validation",
      executionStatus: "succeeded",
      durationMs: 45,
      actorKind: "validator",
    },
    {
      sequenceNumber: 4,
      occurredAt: `2026-09-02T11:30:04${T}`,
      stage: "transaction",
      executionStatus: "succeeded",
      durationMs: 70,
      actorKind: "database",
      metadata: { correctionOf: 2 },
    },
    {
      sequenceNumber: 5,
      occurredAt: `2026-09-02T11:30:08${T}`,
      stage: "correction",
      executionStatus: "succeeded",
      durationMs: 20,
      actorKind: "worker",
      metadata: { successorOf: 2 },
    },
  ]),
];

// ── Import batch (IM-5) ──────────────────────────────────────────────────────

export const importBatches: ImportBatch[] = [
  {
    id: "imp-2526-excel",
    farmId: "bijovira-synthetic",
    importFileHash: "sha256:7c1e...a9",
    requestedBy: "chris",
    startedAt: `2026-08-28T14:00:00${T}`,
    completedAt: `2026-08-28T14:06:32${T}`,
    status: "completed",
    rowsTotal: 96,
    rowsRegistered: 91,
    rowsIgnored: 2,
    rowsDeferred: 3,
  },
];

// ── Authoritative records (post-confirmation) ────────────────────────────────

export const farmActivities: FarmActivity[] = [
  {
    id: 1,
    farmId: "bijovira-synthetic",
    date: "2026-09-01",
    activityType: "hand_weeding",
    durationHours: 2,
    category: "field_work",
    person: "cornelis",
    note: "gewied in de pompoen",
    source: "telegram",
    entryId: "E-0901-01",
    rawText:
      "Vanochtend 2 uur gewied in de pompoen, en nog 1 uur onderhoud tractor.",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [1],
  },
  {
    id: 2,
    farmId: "bijovira-synthetic",
    date: "2026-09-01",
    activityType: "machine_repair",
    durationHours: 1,
    category: "maintenance",
    person: "cornelis",
    note: "onderhoud tractor",
    source: "telegram",
    entryId: "E-0901-01",
    rawText:
      "Vanochtend 2 uur gewied in de pompoen, en nog 1 uur onderhoud tractor.",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [],
  },
  {
    id: 3,
    farmId: "bijovira-synthetic",
    date: "2026-08-31",
    activityType: "irrigation_setup",
    durationHours: 1,
    category: "field_work",
    person: "cornelis",
    note: "pomp aangezet en verplaatst",
    source: "telegram",
    entryId: "E-0901-02",
    rawText: "gisteren 3 uur beregend, pomp de hele dag aan gehad",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: true,
    parcels: [2],
  },
  {
    id: 4,
    farmId: "bijovira-synthetic",
    date: "2026-08-31",
    activityType: "irrigation",
    durationHours: 2,
    category: "field_work",
    quantity: 30,
    unit: "mm",
    person: "cornelis",
    note: "beregening uien noord (run time × pomp-capaciteit)",
    source: "telegram",
    entryId: "E-0901-02",
    rawText: "gisteren 3 uur beregend, pomp de hele dag aan gehad",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: true,
    parcels: [2],
  },
  {
    id: 5,
    farmId: "bijovira-synthetic",
    date: "2026-09-03",
    activityType: "spraying",
    durationHours: 0.5,
    category: "field_work",
    person: "cornelis",
    note: "spuiten achter oost",
    source: "telegram",
    entryId: "E-0902-01",
    rawText: "morgen spuiten op achter oost + ranja 2 l/ha",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [3],
    inputs: [
      {
        product: "ranja (synthetic name)",
        amount: 2,
        unit: "l/ha",
        skalApproved: false,
      },
    ],
  },
  {
    id: 6,
    farmId: "bijovira-synthetic",
    date: "2026-08-28",
    activityType: "hand_weeding",
    durationHours: 1,
    category: "field_work",
    person: "joas",
    note: "1 uur van de lijn voor Joas",
    source: "telegram",
    entryId: "E-0828-01",
    rawText: "2 uur gewied, 1 uur daarvan Joas",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [1],
  },
  {
    id: 7,
    farmId: "bijovira-synthetic",
    date: "2026-08-28",
    activityType: "hand_weeding",
    durationHours: 1,
    category: "field_work",
    person: "cornelis",
    source: "telegram",
    entryId: "E-0828-01",
    rawText: "2 uur gewied, 1 uur daarvan Joas",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [1],
  },
  {
    id: 8,
    farmId: "bijovira-synthetic",
    date: "2026-08-29",
    activityType: "day_note",
    durationHours: 0,
    category: "other",
    note: "veel regen, niet gewerkt — 0 u",
    source: "telegram",
    entryId: "E-0829-01",
    rawText: "vandaag veel regen, niet gewerkt",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [],
  },
  {
    id: 9,
    farmId: "bijovira-synthetic",
    date: "2026-09-01",
    activityType: "hand_weeding",
    durationHours: 2.5,
    category: "field_work",
    person: "cornelis",
    note: "correctie: duur 2 u → 2,5 u naar aanleiding van bericht",
    source: "telegram",
    entryId: "E-0901-01",
    rawText:
      "kun je de wieden van dinsdag naar 2,5 uur zetten? was toch langer",
    reporterId: "tg:cornelis-s",
    dateUncertain: false,
    hoursEstimated: false,
    parcels: [1],
    correctionOf: 1,
  },
];

export const farmObservations: FarmObservation[] = [
  {
    id: 1,
    farmId: "bijovira-synthetic",
    seasonFieldId: 2,
    observedAt: `2026-08-30T08:40:00${T}`,
    concern: "Pest",
    observationText: "uitjpshaantjes aan de noordrand (synthetic)",
    person: "cornelis",
    source: "telegram",
  },
  {
    id: 2,
    farmId: "bijovira-synthetic",
    seasonFieldId: 1,
    activityId: 1,
    observedAt: `2026-09-01T08:15:00${T}`,
    concern: "Weed",
    observationText: "onkruid drukt door tussen de pompoenen",
    person: "cornelis",
    source: "telegram",
  },
  {
    id: 3,
    farmId: "bijovira-synthetic",
    seasonFieldId: 3,
    observedAt: `2026-08-29T18:20:00${T}`,
    concern: "Weather damage",
    observationText: "plasvorming in de koppen na de regen",
    person: "cornelis",
    source: "telegram",
    photoUrl: "s3://synthetic-bucket/obs-3.jpg",
  },
];

// ── Evaluations (QA-2 / WB-7) ────────────────────────────────────────────────

export const evalRuns: EvalRun[] = [
  {
    evalRunId: "evl-001-v42-v43",
    environment: "staging",
    executionMode: "deterministic",
    fixtureReference: "fixtures/golden-set-v7",
    fixtureRedactionState: "synthetic",
    baselineVersion: "vocab-v3",
    candidateVersion: "vocab-v4",
    schemaVersion: "0003",
    startedAt: `2026-09-02T15:40:00${T}`,
    endedAt: `2026-09-02T15:52:10${T}`,
    verdict: "pass",
    retentionClass: "standard",
  },
  {
    evalRunId: "evl-002-v43-v44",
    environment: "staging",
    executionMode: "deterministic",
    fixtureReference: "fixtures/golden-set-v7",
    fixtureRedactionState: "synthetic",
    baselineVersion: "vocab-v4",
    candidateVersion: "prompt-pc:c2f9e1",
    schemaVersion: "0003",
    startedAt: `2026-09-03T10:15:00${T}`,
    endedAt: `2026-09-03T10:29:41${T}`,
    verdict: "fail",
    retentionClass: "standard",
  },
  {
    evalRunId: "evl-003-live-cost",
    environment: "staging",
    executionMode: "live",
    fixtureReference: "fixtures/latency-sample-v2",
    fixtureRedactionState: "redacted",
    baselineVersion: "app-2026.09.0",
    candidateVersion: "app-2026.09.1",
    schemaVersion: "0003",
    startedAt: `2026-09-03T11:30:00${T}`,
    retentionClass: "short",
  },
];

export const evalCaseResults: EvalCaseResult[] = [
  // evl-001: candidate preserved behaviour — pass
  {
    id: 1,
    evalRunId: "evl-001-v42-v43",
    caseId: "G1-two-activities-one-duration",
    runId: "afd10dbc-eabb-4efc-9acb-cfbdab0def11",
    expectedOutcome: "2 rows, hours split by answer",
    actualOutcome: "2 rows, hours split by answer",
    fieldDiff: {},
    invariantResults: { no_drop: true, no_invent: true },
    verdict: "pass",
    retryCount: 0,
    latencyMs: 1850,
    tokenCount: 1420,
    costAmount: 0.0021,
  },
  {
    id: 2,
    evalRunId: "evl-001-v42-v43",
    caseId: "G2-parcel-by-crop-single",
    expectedOutcome: "resolve to uien noord",
    actualOutcome: "resolve to uien noord",
    fieldDiff: {},
    invariantResults: { no_invent: true },
    verdict: "pass",
    retryCount: 0,
    latencyMs: 1610,
    tokenCount: 1180,
    costAmount: 0.0017,
  },
  {
    id: 3,
    evalRunId: "evl-001-v42-v43",
    caseId: "G3-spraying-asks-product",
    expectedOutcome: "ask product + dose before write",
    actualOutcome: "ask product + dose before write",
    fieldDiff: {},
    invariantResults: { ask_before_write: true },
    verdict: "pass",
    retryCount: 0,
    latencyMs: 1730,
    tokenCount: 1290,
    costAmount: 0.0019,
  },
  {
    id: 4,
    evalRunId: "evl-001-v42-v43",
    caseId: "G4-irrigation-split",
    expectedOutcome: "irrigation_setup + irrigation(mm)",
    actualOutcome: "irrigation_setup + irrigation(mm)",
    fieldDiff: {},
    invariantResults: { rule_4: true },
    verdict: "pass",
    retryCount: 1,
    latencyMs: 3120,
    tokenCount: 2210,
    costAmount: 0.0033,
  },
  {
    id: 5,
    evalRunId: "evl-001-v42-v43",
    caseId: "G5-non-work-ignored",
    expectedOutcome: "ignored(reason=not_work), 0 rows",
    actualOutcome: "ignored(reason=not_work), 0 rows",
    fieldDiff: {},
    invariantResults: { no_write: true },
    verdict: "pass",
    retryCount: 0,
    latencyMs: 980,
    tokenCount: 640,
    costAmount: 0.0009,
  },
  {
    id: 6,
    evalRunId: "evl-001-v42-v43",
    caseId: "G6-uncertain-date-confirm",
    expectedOutcome: "date_uncertain=true + confirm",
    actualOutcome: "date_uncertain=true + confirm",
    fieldDiff: {},
    invariantResults: { confirm_before_store: true },
    verdict: "pass",
    retryCount: 0,
    latencyMs: 1440,
    tokenCount: 1010,
    costAmount: 0.0015,
  },
  // evl-002: candidate regressed parcel resolution — fail
  {
    id: 7,
    evalRunId: "evl-002-v43-v44",
    caseId: "G2-parcel-by-crop-single",
    expectedOutcome: "resolve to uien noord",
    actualOutcome: "resolve to achter oost (wrong crop match)",
    fieldDiff: {
      parcels: { expected: "[2]", actual: "[3]" },
    },
    invariantResults: { no_invent: true },
    verdict: "fail",
    retryCount: 0,
    latencyMs: 1580,
    tokenCount: 1150,
    costAmount: 0.0017,
  },
  {
    id: 8,
    evalRunId: "evl-002-v43-v44",
    caseId: "G1-two-activities-one-duration",
    expectedOutcome: "2 rows, hours split by answer",
    actualOutcome: "1 row, hours merged",
    fieldDiff: {
      rows: { expected: "2", actual: "1" },
      duration_hours: { expected: "2.0 + 1.0", actual: "3.0" },
    },
    invariantResults: { no_drop: false },
    verdict: "fail",
    retryCount: 0,
    latencyMs: 1720,
    tokenCount: 1310,
    costAmount: 0.0019,
  },
  {
    id: 9,
    evalRunId: "evl-002-v43-v44",
    caseId: "G4-irrigation-split",
    expectedOutcome: "irrigation_setup + irrigation(mm)",
    actualOutcome: "irrigation_setup + irrigation(mm)",
    fieldDiff: {},
    invariantResults: { rule_4: true },
    verdict: "pass",
    retryCount: 2,
    latencyMs: 4210,
    tokenCount: 2870,
    costAmount: 0.0041,
  },
  {
    id: 10,
    evalRunId: "evl-002-v43-v44",
    caseId: "G7-day-context-zero-hours",
    expectedOutcome: "day_note with 0 h",
    actualOutcome: "day_note with 0 h (flaky on retry)",
    fieldDiff: {},
    invariantResults: { no_write: true },
    verdict: "flaky",
    retryCount: 3,
    latencyMs: 5310,
    tokenCount: 3540,
    costAmount: 0.0052,
  },
];

// ── Operational aggregates (OPS-10 / WB-3) ───────────────────────────────────

export const healthPanels: HealthPanel[] = [
  {
    id: "worker-heartbeat",
    label: "Worker heartbeat",
    health: "healthy",
    detail: "messaging worker polling Telegram · last poll 12 s ago",
    observedAt: `2026-09-03T09:14:02${T}`,
    freshness: "live",
  },
  {
    id: "database",
    label: "Database reachability",
    health: "healthy",
    detail: "repository Postgres · migrations 0001–0003 applied",
    observedAt: `2026-09-03T09:14:00${T}`,
    freshness: "live",
  },
  {
    id: "model-provider",
    label: "Model provider",
    health: "degraded",
    detail:
      "429 rate-limits on Sep 1 (run 2d5a8b… retried 3×); currently serving",
    observedAt: `2026-09-03T09:13:45${T}`,
    freshness: "delayed",
    alertLink: "/runs?errorCode=provider_429",
  },
  {
    id: "queue",
    label: "Queue / backlog",
    health: "healthy",
    detail: "0 queued · 1 running (bge21ecd, retry budget 3/3)",
    observedAt: `2026-09-03T09:14:02${T}`,
    freshness: "live",
  },
  {
    id: "storage",
    label: "Storage",
    health: "healthy",
    detail: "message attachments 62% of quota",
    observedAt: `2026-09-03T06:00:00${T}`,
    freshness: "delayed",
  },
  {
    id: "intake",
    label: "Unmapped intake",
    health: "degraded",
    detail: "3 messages waiting on identity mapping (TG-5)",
    observedAt: `2026-09-03T09:12:00${T}`,
    freshness: "live",
    alertLink: "/intake",
  },
];

export const funnelStages: FunnelStage[] = [
  { id: "received", label: "Received", count: 62 },
  { id: "persisted", label: "Persisted", count: 62 },
  { id: "scoped", label: "Farm-scoped", count: 59 },
  { id: "started", label: "Run started", count: 56 },
  { id: "clarified", label: "Clarified (asked)", count: 9 },
  { id: "validated", label: "Validated", count: 51 },
  { id: "registered", label: "Registered", count: 38, branchOf: "terminal" },
  { id: "observed", label: "Observed", count: 7, branchOf: "terminal" },
  { id: "ignored", label: "Ignored", count: 6, branchOf: "terminal" },
  { id: "expired", label: "Expired", count: 4, branchOf: "terminal" },
  { id: "failed", label: "Failed (undecided)", count: 2, branchOf: "terminal" },
  { id: "running", label: "In flight", count: 2, branchOf: "terminal" },
  {
    id: "quarantined",
    label: "Quarantined (unmapped)",
    count: 3,
    branchOf: "terminal",
  },
];

export const dailyMetrics: DailyMetric[] = [
  {
    date: "2026-08-28",
    p50LatencyMs: 2100,
    p95LatencyMs: 4800,
    tokensIn: 18_400,
    tokensOut: 9_100,
    costAmount: 0.42,
    runs: 11,
  },
  {
    date: "2026-08-29",
    p50LatencyMs: 1900,
    p95LatencyMs: 4100,
    tokensIn: 15_200,
    tokensOut: 7_600,
    costAmount: 0.35,
    runs: 9,
  },
  {
    date: "2026-08-30",
    p50LatencyMs: 1750,
    p95LatencyMs: 3900,
    tokensIn: 11_800,
    tokensOut: 5_900,
    costAmount: 0.27,
    runs: 7,
  },
  {
    date: "2026-08-31",
    p50LatencyMs: 2050,
    p95LatencyMs: 5200,
    tokensIn: 16_900,
    tokensOut: 8_400,
    costAmount: 0.39,
    runs: 10,
  },
  {
    date: "2026-09-01",
    p50LatencyMs: 2400,
    p95LatencyMs: 8900,
    tokensIn: 22_600,
    tokensOut: 11_200,
    costAmount: 0.58,
    runs: 14,
  },
  {
    date: "2026-09-02",
    p50LatencyMs: 1850,
    p95LatencyMs: 4300,
    tokensIn: 19_300,
    tokensOut: 9_600,
    costAmount: 0.44,
    runs: 12,
  },
  {
    date: "2026-09-03",
    p50LatencyMs: 1780,
    p95LatencyMs: 3900,
    tokensIn: 8_100,
    tokensOut: 4_000,
    costAmount: 0.19,
    runs: 5,
  },
];

// ── Lookups ──────────────────────────────────────────────────────────────────

export function getFarm(farmId: string): Farm | undefined {
  return farms.find((farm) => farm.farmId === farmId);
}

export function getField(fieldId: number): SeasonField | undefined {
  return seasonFields.find((field) => field.id === fieldId);
}

export function getMessage(
  id: number | undefined,
): RegistrationMessage | undefined {
  if (id === undefined) {
    return undefined;
  }
  return registrationMessages.find((message) => message.id === id);
}

export function getRun(runId: string): AgentRun | undefined {
  return agentRuns.find((run) => run.runId === runId);
}

export function getRunAttempts(runId: string): AgentRunAttempt[] {
  return agentRunAttempts
    .filter((attempt) => attempt.runId === runId)
    .sort((a, b) => a.attemptNumber - b.attemptNumber);
}

export function getRunEvents(runId: string): AgentRunEvent[] {
  return agentRunEvents
    .filter((event) => event.runId === runId)
    .sort((a, b) => a.sequenceNumber - b.sequenceNumber);
}

export function getActivitiesByEntry(
  entryId: string | undefined,
): FarmActivity[] {
  if (!entryId) {
    return [];
  }
  return farmActivities.filter(
    (activity) => activity.entryId === entryId && !activity.correctionOf,
  );
}

export function getCorrectionsFor(activityId: number): FarmActivity[] {
  return farmActivities.filter(
    (activity) => activity.correctionOf === activityId,
  );
}

export function getImportBatch(
  id: string | undefined,
): ImportBatch | undefined {
  if (!id) {
    return undefined;
  }
  return importBatches.find((batch) => batch.id === id);
}

export function getEvalRun(evalRunId: string): EvalRun | undefined {
  return evalRuns.find((evalRun) => evalRun.evalRunId === evalRunId);
}

export function getEvalCases(evalRunId: string): EvalCaseResult[] {
  return evalCaseResults.filter((result) => result.evalRunId === evalRunId);
}

export function getObservationsForActivity(
  activityId: number,
): FarmObservation[] {
  return farmObservations.filter(
    (observation) => observation.activityId === activityId,
  );
}

export const unmappedIntake: RegistrationMessage[] =
  registrationMessages.filter(
    (message) => message.identityState === "unmapped",
  );
